name: easy_vacation
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  app_links: ^6.4.1
  shared_preferences: ^2.2.2
  http: ^1.2.0         # HTTP client for API requests
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  latlong2: ^0.9.0     # Add this for coordinates
  flutter_bloc: ^9.1.1
  font_awesome_flutter: ^10.7.0
  sqflite: ^2.4.2
  world_flags: ^2.9.1
  country_icons: ^3.0.0
  table_calendar: ^3.0.9

  image_picker: ^1.0.7
  image: ^4.3.0        # Image processing for compression
  intl: ^0.20.2
  path_provider: ^2.1.0
  
  # COMMENT OUT problematic packages temporarily
  permission_handler: ^12.0.1
  flutter_map: ^8.2.2  # Add this
  cached_network_image: ^3.4.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ev_icon.png"

flutter_native_splash:
  color: "#62C3ED"
  android: true
  ios: true
  web: false
  android_12:
    color: "#62C3ED"