name: easy_vacation
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.9.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  sqflite: ^2.4.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets: 

    #- assets/images/app_images/welcome_images/
    #- assets/images/app_images/carousel_images/
    - assets/images/
