name: easy_vacation
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  flutter_bloc: ^9.1.1
  font_awesome_flutter: ^10.7.0
  sqflite: ^2.4.2
  world_flags: ^2.9.1
  country_icons: ^3.0.0

  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ev_icon.png"

flutter_native_splash:
  color: "#62C3ED"
  android: true
  ios: true
  web: false
  # Remove image-related lines completely if you don't have a logo
  android_12:
    color: "#62C3ED"